spring:
  datasource:
    url: jdbc:mysql://uat-db:3306/librarydb
    username: uat_user
    password: uat_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false

server:
  port: 8083

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: false